@Gatekeeper2024_HostAddress = http://localhost:5290

# Вход
POST {{Gatekeeper2024_HostAddress}}/auth/
Accept: application/json

{
    "type": "NORMAL",
    "keyHex": "6404656F",
    "direction": 2,
    "accessPoint": 1
}

###

# Вход простого смертного
POST {{Gatekeeper2024_HostAddress}}/auth/
Accept: application/json

{
    "type": "NORMAL",
    "keyHex": "6404BDD8",
    "direction": 2,
    "accessPoint": 1
}

###

# Вход несуществующего
POST {{Gatekeeper2024_HostAddress}}/auth/
Accept: application/json

{
    "type": "NORMAL",
    "keyHex": "6404656E",
    "direction": 2,
    "accessPoint": 1
}

###

# Выход
POST {{Gatekeeper2024_HostAddress}}/auth/
Accept: application/json

{
    "type": "NORMAL",
    "keyHex": "6404656F",
    "direction": 1,
    "accessPoint": 4
}

###

# Остановка сервера
GET {{Gatekeeper2024_HostAddress}}/api/stop

###

# Получение истории
GET {{Gatekeeper2024_HostAddress}}/api/history

###

# Получение статистики
GET {{Gatekeeper2024_HostAddress}}/api/stat

###

# Текущее состояние
GET {{Gatekeeper2024_HostAddress}}/api/state

###

# Могут входит только свои
GET {{Gatekeeper2024_HostAddress}}/api/blat?on=true

###

# Библиотека открыта для посещений
GET {{Gatekeeper2024_HostAddress}}/api/blat?on=false

###
