version: 5.0.0.{build}
configuration: Debug
image: Visual Studio 2019

environment:
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: choco install miktex
- cmd: python -m pip install --upgrade pip
- cmd: pip install --upgrade pygount sphinx sphinx_rtd_theme
- cmd: pygount -f summary Source/Libs -s cs -N "*.Designer.cs" -F "obj"
- cmd: pygount -f summary Source/Tests -s cs -N "*.Designer.cs" -F "obj"
- cmd: pygount -f summary Source/Apps -s cs -N "*.Designer.cs" -F "obj"
- cmd: dotnet --info

build_script:
- cmd: dotnet restore                                    Source/ManagedIrbis5-windows.sln
- cmd: dotnet build --no-restore --configuration Release Source/ManagedIrbis5-windows.sln

test_script:
- cmd: dotnet test --no-restore --no-build --configuration Release Source/ManagedIrbis5-windows.sln
- cmd: dotnet run  --no-restore --no-build --configuration Release --project Source/Benchmarks/CoreBenchmarks/CoreBenchmarks.csproj

after_build:
- dotnet pack --no-restore --no-build --configuration Release Source/ManagedIrbis5-windows.sln
- cd 

artifacts:
  - path: '**\*.nupkg'
