version: 5.0.0.{build}
configuration: Debug
image: Visual Studio 2022

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

init:
  - git config --global core.autocrlf true

before_build:
- systeminfo
- '"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"'
- python -m pip install --upgrade pip
- pip install --upgrade pygount sphinx sphinx_rtd_theme
- pygount -f summary Source/Libs                       -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Libs/AM.Core5/Source       -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Libs/ManagedIrbis5/Source  -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Libs/AM.Scripting/Source   -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Tests                      -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Apps                       -s cs -N "*.Designer.cs" -F "obj"
- dotnet --info
- dotnet restore Source\Utils\Utils.sln
- dotnet build --no-restore --configuration Release Source\Utils\Utils.sln

build_script:
- dotnet restore                                    Source\ManagedIrbis5-windows.sln
- dotnet restore                                    Source\TinyClient.sln
- dotnet build --no-restore --configuration Release Source\ManagedIrbis5-windows.sln
- dotnet build --no-restore --configuration Release Source\TinyClient.sln

test_script:
- dotnet test --no-restore --no-build --configuration Release --settings sequential.runsettings Source\ManagedIrbis5-windows.sln
- dotnet run  --no-restore --no-build --configuration Release --project                         Source\Tests\PftTests\PftTests.csproj
- dotnet run  --no-restore --no-build --configuration Release --project                         Source\Tests\BarsikTestRunner\BarsikTestRunner.csproj

after_build:
- dotnet pack    --no-restore --no-build --configuration Release --include-symbols --include-source --output NuGet   Source\ManagedIrbis5-publish.sln
- dotnet pack    --no-restore --no-build --configuration Release --include-symbols --include-source --output NuGet   Source\Libs\TinyClient\TinyClient.csproj
- dotnet publish --no-restore --no-build --configuration Release                                    --output Publish Source\ManagedIrbis5-publish.sln
- dotnet publish --no-restore --no-build --configuration Release                                    --output Publish Source\Libs\TinyClient\TinyClient.csproj

artifacts:
  - path: 'NuGet\'
    name: 'NuGet packages'

  - path: 'Publish\'
    name: 'Binaries'
