version: 5.0.0.{build}
configuration: Debug
image: Visual Studio 2019

environment:
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- systeminfo
- "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
- python -m pip install --upgrade pip
- pip install --upgrade pygount sphinx sphinx_rtd_theme
- pygount -f summary Source/Libs -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Tests -s cs -N "*.Designer.cs" -F "obj"
- pygount -f summary Source/Apps -s cs -N "*.Designer.cs" -F "obj"
- dotnet --info
- dotnet tool install -g JetBrains.ReSharper.GlobalTools

build_script:
- dotnet restore                                    Source/ManagedIrbis5-windows.sln
- dotnet build --no-restore --configuration Release Source/ManagedIrbis5-windows.sln

test_script:
- dotnet test --no-restore --no-build --configuration Release --settings sequential.runsettings Source/ManagedIrbis5-windows.sln
- dotnet run  --no-restore --no-build --configuration Release --project Source/Tests/PftTests/PftTests.csproj

after_build:
- dotnet pack --no-restore --no-build --configuration Release Source/ManagedIrbis5-windows.sln
- jb inspectcode --verbosity=OFF -o=inspectcode-result.xml Source\ManagedIrbis5-windows.sln
- jb dupfinder   --verbosity=OFF -o=dupfinder-result.xml   Source\ManagedIrbis5-windows.sln
- cd

artifacts:
  - path: '**\*.nupkg'
  - path: 'inspectcode-result.xml'
  - path: 'dupfinder-result.xml'
