version: 5.0.0.{build}
configuration: Debug
image: Visual Studio 2022

environment:
  DOTNET_CLI_UI_LANGUAGE: en
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  PATH: C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

init:
  - git config --global core.autocrlf true

before_build:
- systeminfo
- '"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"'
- rem python -m pip install --upgrade pip
- rem pip install --upgrade pygount sphinx sphinx_rtd_theme
- rem pygount -f summary Source/Libs                       -s cs -N "*.Designer.cs" -F "obj"
- rem pygount -f summary Source/Libs/AM.Core5/Source       -s cs -N "*.Designer.cs" -F "obj"
- rem pygount -f summary Source/Libs/ManagedIrbis5/Source  -s cs -N "*.Designer.cs" -F "obj"
- rem pygount -f summary Source/Libs/AM.Scripting/Source   -s cs -N "*.Designer.cs" -F "obj"
- rem pygount -f summary Source/Tests                      -s cs -N "*.Designer.cs" -F "obj"
- rem pygount -f summary Source/Apps                       -s cs -N "*.Designer.cs" -F "obj"
- appveyor DownloadFile https://dot.net/v1/dotnet-install.ps1
- powershell -ExecutionPolicy unrestricted ./dotnet-install.ps1 -Version 7.0.100-rc.1.22431.12
- dotnet --info
- dotnet tool install --tool-path . nbgv
- dotnet tool install --tool-path . coverlet.console
- nbgv cloud
- dotnet build --configuration Release Source\Utils\Utils-windows.sln

build_script:
- dotnet build --configuration Release Source\ManagedIrbis5-windows.sln
- dotnet build --configuration Release Source\TinyClient.sln

test_script:
- dotnet test --no-restore --no-build --configuration Release --settings sequential.runsettings /p:CollectCoverage=true Source\ManagedIrbis5-windows.sln
- dotnet run  --no-restore --no-build --configuration Release --project                                                 Source\Tests\PftTests\PftTests.csproj
- dotnet run  --no-restore --no-build --configuration Release --project                                                 Source\Tests\BarsikTestRunner\BarsikTestRunner.csproj

after_build:
- dotnet pack    --no-restore --no-build --configuration Release --output NuGet   Source\ManagedIrbis5-publish.sln
- dotnet pack    --no-restore --no-build --configuration Release --output NuGet   Source\Libs\TinyClient\TinyClient.csproj
- dotnet publish --no-restore --no-build --configuration Release --output Publish Source\ManagedIrbis5-publish.sln
- dotnet publish --no-restore --no-build --configuration Release --output Publish Source\Libs\TinyClient\TinyClient.csproj

artifacts:
  - path: 'NuGet\'
    name: 'NuGet packages'

  - path: 'Publish\'
    name: 'Binaries'
