version: 5.0.0.{build}
configuration: Debug
image: Visual Studio 2019 Preview

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: C:\Python36-x64\python -m pip install --upgrade pip
- cmd: C:\Python36-x64\Scripts\pip install --upgrade pygount
- cmd: C:\Python36-x64\Scripts\pygount -f summary Source/Libs -s cs -N "*.Designer.cs" -F "obj"
- cmd: dotnet --info

build_script:
- cmd: dotnet restore Source/ManagedIrbis5.sln
- cmd: dotnet build --no-restore --configuration Release Source/ManagedIrbis5.sln

test_script:
- cmd: dotnet test --no-restore --no-build --configuration Release Source/ManagedIrbis5.sln

after_build:
- cmd: dotnet pack -no-restore --no-build --configuration Release Source/ManagedIrbis5.sln
