// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

// ReSharper disable CheckNamespace
// ReSharper disable CommentTypo
// ReSharper disable StringLiteralTypo
// ReSharper disable UnusedMember.Global

/* Studio.cs -- известные фотостудии
 * Ars Magna project, http://arsmagna.ru
 */

#nullable enable

namespace TheNude;

/// <summary>
/// Известные фотостудии.
/// </summary>
public sealed class Studio
{
    #region Properties

    /// <summary>
    /// Числовой код студии.
    /// </summary>
    public required int Code { get; set; }

    /// <summary>
    /// Название студии.
    /// </summary>
    public required string Title { get; set; }

    #endregion

    #region Known studios

    public static readonly Studio[] KnownStudios =
    {
        new() { Code = 1054, Title = "1000 facials" },
        new() { Code = 477,  Title = "18 Pussy Club" },
        new() { Code = 355,  Title = "18eighteen" },
        new() { Code = 316,  Title = "18magazine" },
        new() { Code = 1406, Title = "18vr" },
        new() { Code = 45,   Title = "1by-day" },
        new() { Code = 300,  Title = "1by-day Archives" },
        new() { Code = 525,  Title = "1pondo" },
        new() { Code = 737,  Title = "21naturals" },
        new() { Code = 738,  Title = "21sextreme" },
        new() { Code = 461,  Title = "21sextury" },
        new() { Code = 816,  Title = "4k-star" },
        new() { Code = 1365, Title = "5kporn" },
        new() { Code = 1366, Title = "5kteens" },
        new() { Code = 513,  Title = "66beauty" },
        new() { Code = 633,  Title = "66casting" },
        new() { Code = 514,  Title = "66latex" },
        new() { Code = 635,  Title = "66models" },
        new() { Code = 634,  Title = "66plastic" },
        new() { Code = 357,  Title = "ActionGirls" },
        new() { Code = 683,  Title = "ActionGirls Heroes" },
        new() { Code = 684,  Title = "ActionGirls Mercs" },
        new() { Code = 1549, Title = "Addicted2girls" },
        new() { Code = 1392, Title = "Adultallstars" },
        new() { Code = 1516, Title = "Adultmemberzone" },
        new() { Code = 508,  Title = "alisonangel" },
        new() { Code = 1439, Title = "allblackx" },
        new() { Code = 822,  Title = "allgirlnudemassage" },
        new() { Code = 719,  Title = "allgravure" },
        new() { Code = 1412, Title = "allherluv" },
        new() { Code = 1316, Title = "allover30" },
        new() { Code = 876,  Title = "allsortsofgirls" },
        new() { Code = 1373, Title = "allvr" },
        new() { Code = 579,  Title = "alpgirls" },
        new() { Code = 89,   Title = "als Archive" },
        new() { Code = 733,  Title = "als Scan" },
        new() { Code = 408,  Title = "alsangels" },
        new() { Code = 464,  Title = "alsscan" },
        new() { Code = 1566, Title = "alterotic" },
        new() { Code = 752,  Title = "altexclusive" },
        new() { Code = 1592, Title = "amateurcfnm" },
        new() { Code = 861,  Title = "amateurpraguefeet" },
        new() { Code = 333,  Title = "ambya" },
        new() { Code = 36,   Title = "Amour Angels" },
        new() { Code = 639,  Title = "Anal Angels" },
        new() { Code = 901,  Title = "Anal Beauty" },
        new() { Code = 1584, Title = "Analized" },
        new() { Code = 1490, Title = "Anal only" },
        new() { Code = 774,  Title = "Angelablanche" },
        new() { Code = 657,  Title = "angelafterlife" },
        new() { Code = 420,  Title = "anilos" },
        new() { Code = 1260, Title = "antonioclemens" },
        new() { Code = 457,  Title = "apd Nudes" },
        new() { Code = 354,  Title = "argen-teens" },
        new() { Code = 466,  Title = "art-lingerie" },
        new() { Code = 500,  Title = "art-nude-angels" },
        new() { Code = 883,  Title = "artcore-cafe" },
        new() { Code = 5,    Title = "artfemme" },
        new() { Code = 823,  Title = "artnudetattoos" },
        new() { Code = 1261, Title = "artofdanworld" },
        new() { Code = 572,  Title = "artofgloss" },
        new() { Code = 892,  Title = "artoflegs" },
        new() { Code = 707,  Title = "ashgirl" },
        new() { Code = 1553, Title = "asiansexdiary" },
        new() { Code = 258,  Title = "atkarchives" },
        new() { Code = 358,  Title = "atkexotics" },
        new() { Code = 151,  Title = "atkgalleria" },
        new() { Code = 766,  Title = "atkgirlfriends" },
        new() { Code = 152,  Title = "atkhairy" },
        new() { Code = 359,  Title = "atkpetites" },
        new() { Code = 150,  Title = "atkpremium" },
        new() { Code = 771,  Title = "atomicsweet" },
        new() { Code = 455,  Title = "atomicsweet Archives" },
        new() { Code = 750,  Title = "audrey Bitoni" },
        new() { Code = 1297, Title = "averotica" },
        new() { Code = 159,  Title = "averotica Archives" },
        new() { Code = 625,  Title = "axelle Parker" },
        new() { Code = 971,  Title = "aziani" },
        new() { Code = 200,  Title = "aziani Archives" },
        new() { Code = 721,  Title = "azianiiron" },
        new() { Code = 53,   Title = "babelicious" },
        new() { Code = 1306, Title = "baberotica" },
        new() { Code = 1520, Title = "baberoticavr" },
        new() { Code = 681,  Title = "babes" },
        new() { Code = 1266, Title = "babes Unleashed" },
        new() { Code = 1405, Title = "babevr" },
        new() { Code = 1457, Title = "backdoorpov" },
        new() { Code = 709,  Title = "badbentley" },
        new() { Code = 1589, Title = "badfamilypov" },
        new() { Code = 528,  Title = "Bare Maidens" },
        new() { Code = 545,  Title = "Barely Legal" },
        new() { Code = 812,  Title = "bbfilms" },
        new() { Code = 229,  Title = "BeautifulNude" },
        new() { Code = 580,  Title = "beauty-angels" },
        new() { Code = 905,  Title = "beauty4k" },
        new() { Code = 16,   Title = "Beauty is divine" },
        new() { Code = 1376, Title = "bellesa Films" },
        new() { Code = 493,  Title = "bellisimas" },
        new() { Code = 1275, Title = "best-ladies" },
        new() { Code = 824,  Title = "bigboobworship" },
        new() { Code = 1542, Title = "bigcockbully" },
        new() { Code = 667,  Title = "bigtitsglamour" },
        new() { Code = 1421, Title = "bjraw" },
        new() { Code = 1002, Title = "black Is Better" },
        new() { Code = 406,  Title = "blondstars" },
        new() { Code = 23,   Title = "bluenudes" },
        new() { Code = 708,  Title = "bobbistarr" },
        new() { Code = 17,   Title = "bodyinmind" },
        new() { Code = 1548, Title = "bohonude" },
        new() { Code = 753,  Title = "boppingbabes" },
        new() { Code = 1533, Title = "brattymilf" },
        new() { Code = 941,  Title = "brattysis" },
        new() { Code = 222,  Title = "brazzers" },
        new() { Code = 139,  Title = "breath-takers Archives" },
        new() { Code = 1515, Title = "brokenbabes" },
        new() { Code = 1517, Title = "brutalclips" },
        new() { Code = 1238, Title = "burningangel" },
        new() { Code = 499,  Title = "bustynastya" },
        new() { Code = 1575, Title = "bustyworld" },
        new() { Code = 866,  Title = "cafenudes" },
        new() { Code = 1257, Title = "cashmere-cuties" },
        new() { Code = 1593, Title = "cfnmgames" },
        new() { Code = 759,  Title = "charmmodels" },
        new() { Code = 287,  Title = "cherryjul" },
        new() { Code = 912,  Title = "cherrypimps" },
        new() { Code = 976,  Title = "class-nudes" },
        new() { Code = 91,   Title = "clubseventeen" },
        new() { Code = 1461, Title = "cocksuckingchallenge" },
        new() { Code = 814,  Title = "colette" },
        new() { Code = 1391, Title = "college-uniform" },
        new() { Code = 1565, Title = "comeinside" },
        new() { Code = 887,  Title = "cosmid" },
        new() { Code = 661,  Title = "cosplayerotica" },
        new() { Code = 1395, Title = "cosplayfeet" },
        new() { Code = 819,  Title = "covermodels" },
        new() { Code = 600,  Title = "creampie-angels" },
        new() { Code = 948,  Title = "cruelromance" },
        new() { Code = 1510, Title = "cuckhunter" },
        new() { Code = 1561, Title = "cumblastcity" },
        new() { Code = 1551, Title = "cumswappingsis" },
        new() { Code = 34,   Title = "cupids Dart" },
        new() { Code = 79,   Title = "czech-babes" },
        new() { Code = 1389, Title = "darkroomvr" },
        new() { Code = 1573, Title = "darksodomy" },
        new() { Code = 1055, Title = "darkx" },
        new() { Code = 214,  Title = "david-nudes" },
        new() { Code = 55,   Title = "ddfbusty" },
        new() { Code = 264,  Title = "defloration.tv" },
        new() { Code = 330,  Title = "denudeart" },
        new() { Code = 881,  Title = "devilsfilm" },
        new() { Code = 919,  Title = "dfbnetwork" },
        new() { Code = 1496, Title = "diabolic" },
        new() { Code = 170,  Title = "digitalcovergirls" },
        new() { Code = 672,  Title = "digitaldesire" },
        new() { Code = 47,   Title = "digitaldesire Archives" },
        new() { Code = 906,  Title = "dirtycoach" },
        new() { Code = 907,  Title = "dirtydoctor" },
        new() { Code = 18,   Title = "domai" },
        new() { Code = 958,  Title = "domingoview" },
        new() { Code = 784,  Title = "domingoview Archives" },
        new() { Code = 1227, Title = "dorcelclub" },
        new() { Code = 1228, Title = "dorcelvision" },
        new() { Code = 1502, Title = "dothewife" },
        new() { Code = 920,  Title = "downblousejerk" },
        new() { Code = 859,  Title = "driverxxx" },
        new() { Code = 577,  Title = "earlmiller" },
        new() { Code = 114,  Title = "ebina" },
        new() { Code = 1559, Title = "ebonytugs" },
        new() { Code = 1027, Title = "elegantanal" },
        new() { Code = 438,  Title = "eroberlin" },
        new() { Code = 1269, Title = "erokatya" },
        new() { Code = 1270, Title = "eronata" },
        new() { Code = 1248, Title = "erotic-art" },
        new() { Code = 431,  Title = "erotic-flowers" },
        new() { Code = 764,  Title = "eroticax" },
        new() { Code = 656,  Title = "eroticbeauty" },
        new() { Code = 1288, Title = "eroticcecelia" },
        new() { Code = 1252, Title = "eroticdesire" },
        new() { Code = 677,  Title = "eroticsnap" },
        new() { Code = 1369, Title = "eroutique" },
        new() { Code = 682,  Title = "erro-arch Movies" },
        new() { Code = 2,    Title = "Errotica Archives" },
        new() { Code = 891,  Title = "erroticum" },
        new() { Code = 741,  Title = "eternaldesire" },
        new() { Code = 520,  Title = "ethernudes" },
        new() { Code = 490,  Title = "eu-nudes" },
        new() { Code = 782,  Title = "eurobabefacials" },
        new() { Code = 216,  Title = "eurogirlsongirls" },
        new() { Code = 761,  Title = "euronudes" },
        new() { Code = 88,   Title = "euronudes Archives" },
        new() { Code = 1554, Title = "eurosexdiary" },
        new() { Code = 416,  Title = "eurosinsations" },
        new() { Code = 247,  Title = "euroteenerotica" },
        new() { Code = 33,   Title = "evasgarden" },
        new() { Code = 418,  Title = "eveangelofficial" },
        new() { Code = 710,  Title = "evilaiden" },
        new() { Code = 855,  Title = "evilangel" },
        new() { Code = 393,  Title = "exclusiveteenporn" },
        new() { Code = 135,  Title = "exoticfootmodels" },
        new() { Code = 492,  Title = "explicite-art" },
        new() { Code = 1523, Title = "exposedlatinas" },
        new() { Code = 687,  Title = "exposednurses" },
        new() { Code = 603,  Title = "eyecandyavenue Archives" },
        new() { Code = 1532, Title = "facials4k" },
        new() { Code = 1567, Title = "facialsforever" },
        new() { Code = 775,  Title = "famegirls" },
        new() { Code = 1556, Title = "familylust" },
        new() { Code = 1423, Title = "familyswap" },
        new() { Code = 1137, Title = "fantasymassage" },
        new() { Code = 576,  Title = "fedorovhd" },
        new() { Code = 1292, Title = "feelmevr" },
        new() { Code = 1455, Title = "feetishpov" },
        new() { Code = 694,  Title = "feetluv" },
        new() { Code = 3,    Title = "femjoy" },
        new() { Code = 570,  Title = "femjoy Archives" },
        new() { Code = 230,  Title = "femjoy Video" },
        new() { Code = 308,  Title = "femmephotography" },
        new() { Code = 1241, Title = "ferr-art" },
        new() { Code = 1518, Title = "fhuta" },
        new() { Code = 705,  Title = "figurebaby" },
        new() { Code = 1530, Title = "filthykings" },
        new() { Code = 1498, Title = "finishhim" },
        new() { Code = 189,  Title = "first-nude" },
        new() { Code = 898,  Title = "firstbgg" },
        new() { Code = 1429, Title = "fistertwister" },
        new() { Code = 1598, Title = "fit18" },
        new() { Code = 1234, Title = "fitting-room" },
        new() { Code = 644,  Title = "flashybabes" },
        new() { Code = 1317, Title = "flexyteens" },
        new() { Code = 44,   Title = "fm-teens" },
        new() { Code = 627,  Title = "foot-art" },
        new() { Code = 1396, Title = "footfetishbeauties" },
        new() { Code = 1562, Title = "freeusemilf" },
        new() { Code = 49,   Title = "fritzryan" },
        new() { Code = 28,   Title = "ftvgirls" },
        new() { Code = 877,  Title = "ftvmilfs" },
        new() { Code = 1474, Title = "fuckingawesome" },
        new() { Code = 529,  Title = "fuckmyjeans" },
        new() { Code = 501,  Title = "fuckstudies" },
        new() { Code = 785,  Title = "galitsin Comrades" },
        new() { Code = 191,  Title = "galitsin-archives" },
        new() { Code = 173,  Title = "galitsin-news" },
        new() { Code = 195,  Title = "galitsinvideo" },
        new() { Code = 437,  Title = "gallery-carre" },
        new() { Code = 1467, Title = "genuinesin" },
        new() { Code = 1581, Title = "gingerpatch" },
        new() { Code = 301,  Title = "giorgio Grandi" },
        new() { Code = 211,  Title = "girlfolio" },
        new() { Code = 1470, Title = "girlgirl" },
        new() { Code = 1594, Title = "girlsabuseguys" },
        new() { Code = 1466, Title = "girlsfuckgirls" },
        new() { Code = 193,  Title = "girlsinnature" },
        new() { Code = 1044, Title = "girlsway" },
        new() { Code = 235,  Title = "glam4ever" },
        new() { Code = 509,  Title = "glamandart" },
        new() { Code = 632,  Title = "glamazones" },
        new() { Code = 37,   Title = "glamdeluxe" },
        new() { Code = 770,  Title = "glamourflower" },
        new() { Code = 253,  Title = "glamourflower Archives" },
        new() { Code = 970,  Title = "glamourstarslive" },
        new() { Code = 1237, Title = "gloryholesecrets" },
        new() { Code = 1507, Title = "glosstightsglamour" },
        new() { Code = 491,  Title = "goddessnudes" },
        new() { Code = 1504, Title = "goldenslut" },
        new() { Code = 602,  Title = "goldnude" },
        new() { Code = 1541, Title = "gotfilled" },
        new() { Code = 747,  Title = "gravure" },
        new() { Code = 848,  Title = "gyno-x" },
        new() { Code = 622,  Title = "hairytwatter" },
        new() { Code = 58,   Title = "handsonhardcore" },
        new() { Code = 825,  Title = "happynakedteengirls" },
        new() { Code = 949,  Title = "hardtied" },
        new() { Code = 797,  Title = "hardx" },
        new() { Code = 4,    Title = "harris-archives" },
        new() { Code = 697,  Title = "hayleys Secrets" },
        new() { Code = 826,  Title = "hdstudionudes" },
        new() { Code = 1279, Title = "heal-fit" },
        new() { Code = 257,  Title = "hegre-archives" },
        new() { Code = 11,   Title = "hegre-art" },
        new() { Code = 778,  Title = "hegre-art Massage" },
        new() { Code = 251,  Title = "hegre-art Video" },
        new() { Code = 686,  Title = "hidenylons" },
        new() { Code = 411,  Title = "hollyrandall" },
        new() { Code = 595,  Title = "hollyrandall Archives" },
        new() { Code = 1545, Title = "hookuphotshot" },
        new() { Code = 56,   Title = "hotlegsandfeet" },
        new() { Code = 1418, Title = "hotmilfsfuck" },
        new() { Code = 352,  Title = "houseoftaboo" },
        new() { Code = 547,  Title = "hustler" },
        new() { Code = 1094, Title = "immorallive" },
        new() { Code = 950,  Title = "infernalrestraints" },
        new() { Code = 1597, Title = "inserted" },
        new() { Code = 255,  Title = "inthecrack" },
        new() { Code = 1456, Title = "intimatepov" },
        new() { Code = 659,  Title = "istripper" },
        new() { Code = 1488, Title = "japanhdv" },
        new() { Code = 1511, Title = "japanlust" },
        new() { Code = 1503, Title = "jeffsmodels" },
        new() { Code = 314,  Title = "jennissecrets" },
        new() { Code = 1512, Title = "joibabes" },
        new() { Code = 1422, Title = "jonathanjordanxxx" },
        new() { Code = 1596, Title = "joybear" },
        new() { Code = 566,  Title = "joymii" },
        new() { Code = 574,  Title = "jts Archives" },
        new() { Code = 594,  Title = "juliland" },
        new() { Code = 115,  Title = "just-nude" },
        new() { Code = 14,   Title = "justteensite" },
        new() { Code = 396,  Title = "justteensporn" },
        new() { Code = 1276, Title = "karissa-diamond" },
        new() { Code = 67,   Title = "karupspc" },
        new() { Code = 1251, Title = "katya Clover" },
        new() { Code = 1045, Title = "kellymadison" },
        new() { Code = 1407, Title = "kinkvr" },
        new() { Code = 249,  Title = "kissak" },
        new() { Code = 671,  Title = "kissak2" },
        new() { Code = 348,  Title = "kscans" },
        new() { Code = 1590, Title = "ladyvoyeurs" },
        new() { Code = 676,  Title = "layered-nylons" },
        new() { Code = 487,  Title = "lazonamodelos" },
        new() { Code = 1388, Title = "legsex" },
        new() { Code = 732,  Title = "legsfactor" },
        new() { Code = 658,  Title = "lesbea" },
        new() { Code = 1043, Title = "lesbianx" },
        new() { Code = 1513, Title = "lesworship" },
        new() { Code = 938,  Title = "letsdoeit" },
        new() { Code = 551,  Title = "lia19" },
        new() { Code = 968,  Title = "lingerietales" },
        new() { Code = 1442, Title = "littlecaprice-dreams" },
        new() { Code = 1595, Title = "littledick" },
        new() { Code = 506,  Title = "litu100" },
        new() { Code = 593,  Title = "lizzie-secret" },
        new() { Code = 680,  Title = "lonelybit" },
        new() { Code = 903,  Title = "love Hairy" },
        new() { Code = 628,  Title = "love4socks" },
        new() { Code = 1531, Title = "loveherboobs" },
        new() { Code = 1430, Title = "loveherfeet" },
        new() { Code = 32,   Title = "lsgmodels" },
        new() { Code = 321,  Title = "lsgvideo" },
        new() { Code = 585,  Title = "lucyvanangel" },
        new() { Code = 1371, Title = "lustreality" },
        new() { Code = 611,  Title = "magic-erotica" },
        new() { Code = 760,  Title = "magiksex" },
        new() { Code = 218,  Title = "maxarchives" },
        new() { Code = 1,    Title = "MC-Nudes" },
        new() { Code = 236,  Title = "MC-Nudes Video" },
        new() { Code = 1557, Title = "meanmassage" },
        new() { Code = 1290, Title = "melena Maria Rya" },
        new() { Code = 621,  Title = "melina" },
        new() { Code = 441,  Title = "metangels" },
        new() { Code = 6,    Title = "MetArt" },
        new() { Code = 336,  Title = "MetArt Archives" },
        new() { Code = 886,  Title = "MetArt X" },
        new() { Code = 185,  Title = "metcn" },
        new() { Code = 183,  Title = "metgirls" },
        new() { Code = 7,    Title = "MetModels" },
        new() { Code = 597,  Title = "MetMovies" },
        new() { Code = 742,  Title = "michaelninn" },
        new() { Code = 725,  Title = "michaelninn Archives" },
        new() { Code = 821,  Title = "michaelstycket" },
        new() { Code = 902,  Title = "milena Angel" },
        new() { Code = 1383, Title = "milfed" },
        new() { Code = 1527, Title = "milftrip" },
        new() { Code = 1443, Title = "milfvr" },
        new() { Code = 695,  Title = "milkybabes" },
        new() { Code = 1411, Title = "missax" },
        new() { Code = 1465, Title = "mixedx" },
        new() { Code = 187,  Title = "modeljoint" },
        new() { Code = 1544, Title = "moderndaysins" },
        new() { Code = 1093, Title = "mommyblowsbest" },
        new() { Code = 799,  Title = "momsteachsex" },
        new() { Code = 1563, Title = "momswap" },
        new() { Code = 1580, Title = "morepov" },
        new() { Code = 54,   Title = "moreystudios" },
        new() { Code = 678,  Title = "moreystudios2" },
        new() { Code = 8,    Title = "mplstudios" },
        new() { Code = 467,  Title = "mpv Models" },
        new() { Code = 19,   Title = "muse" },
        new() { Code = 762,  Title = "my Naked Dolls" },
        new() { Code = 1038, Title = "myfamilypies" },
        new() { Code = 50,   Title = "myglamoursite" },
        new() { Code = 1348, Title = "mylf" },
        new() { Code = 1464, Title = "mylked" },
        new() { Code = 390,  Title = "mylovelygirls" },
        new() { Code = 1428, Title = "mypervyfamily" },
        new() { Code = 169,  Title = "mypreciousvirgins" },
        new() { Code = 40,   Title = "myprivateglamour" },
        new() { Code = 175,  Title = "mystique-mag" },
        new() { Code = 776,  Title = "n-timate" },
        new() { Code = 916,  Title = "nadine-j" },
        new() { Code = 518,  Title = "naked-art" },
        new() { Code = 827,  Title = "nakedgymgirls" },
        new() { Code = 1236, Title = "nakety" },
        new() { Code = 1291, Title = "nancy Ace" },
        new() { Code = 582,  Title = "nancymurrian" },
        new() { Code = 1438, Title = "naughtyamericavr" },
        new() { Code = 935,  Title = "naughtymag" },
        new() { Code = 1540, Title = "naughtynatural" },
        new() { Code = 442,  Title = "newnudegirls" },
        new() { Code = 184,  Title = "newworldnudes" },
        new() { Code = 168,  Title = "nextdoor-models" },
        new() { Code = 534,  Title = "nextdoor-models2" },
        new() { Code = 940,  Title = "nfbusty" },
        new() { Code = 813,  Title = "noboring" },
        new() { Code = 888,  Title = "nocturnalgirls" },
        new() { Code = 581,  Title = "nu-russian-art" },
        new() { Code = 181,  Title = "nubile-art" },
        new() { Code = 702,  Title = "nubilefilms" },
        new() { Code = 909,  Title = "nubilegirlshd" },
        new() { Code = 439,  Title = "nubilegirlshd Archive" },
        new() { Code = 815,  Title = "Nubiles" },
        new() { Code = 62,   Title = "Nubiles Archive" },
        new() { Code = 798,  Title = "Nubiles Casting" },
        new() { Code = 172,  Title = "Nud-Art" },
        new() { Code = 726,  Title = "nude-archives" },
        new() { Code = 194,  Title = "Nude in Russia" },
        new() { Code = 749,  Title = "nudebeauties" },
        new() { Code = 407,  Title = "nudeidea" },
        new() { Code = 22,   Title = "nudeillusion" },
        new() { Code = 1305, Title = "nudex" },
        new() { Code = 1514, Title = "nudeyogaporn" },
        new() { Code = 176,  Title = "NuDolls" },
        new() { Code = 573,  Title = "NuDolls Video" },
        new() { Code = 867,  Title = "nuerotica" },
        new() { Code = 217,  Title = "nuglam" },
        new() { Code = 765,  Title = "nutabu" },
        new() { Code = 690,  Title = "nyloncovered" },
        new() { Code = 1393, Title = "nylonfeetlove" },
        new() { Code = 910,  Title = "nylonsx" },
        new() { Code = 1508, Title = "nylonup" },
        new() { Code = 322,  Title = "obj Archives" },
        new() { Code = 1028, Title = "office Obsession" },
        new() { Code = 1454, Title = "officepov" },
        new() { Code = 448,  Title = "old-n-young" },
        new() { Code = 122,  Title = "oldje" },
        new() { Code = 1271, Title = "only-costumes" },
        new() { Code = 944,  Title = "only-opaques" },
        new() { Code = 158,  Title = "only-opaques Covers" },
        new() { Code = 1272, Title = "only-sportswear" },
        new() { Code = 57,   Title = "onlyblowjob" },
        new() { Code = 1522, Title = "onlylookingarchives" },
        new() { Code = 942,  Title = "onlysecretaries" },
        new() { Code = 349,  Title = "onlysecretaries Covers" },
        new() { Code = 943,  Title = "onlysilkandsatin" },
        new() { Code = 350,  Title = "onlysilkandsatin Covers" },
        new() { Code = 945,  Title = "onlytease" },
        new() { Code = 157,  Title = "onlytease Covers" },
        new() { Code = 736,  Title = "onlyteenblowjobs" },
        new() { Code = 1145, Title = "openlife" },
        new() { Code = 615,  Title = "orgasms" },
        new() { Code = 1560, Title = "over40handjobs" },
        new() { Code = 800,  Title = "passionhd" },
        new() { Code = 82,   Title = "penthouse" },
        new() { Code = 12,   Title = "peterjanhans" },
        new() { Code = 728,  Title = "petgirls" },
        new() { Code = 849,  Title = "petiteballerinasfucked" },
        new() { Code = 833,  Title = "petitehdporn" },
        new() { Code = 1452, Title = "petitepov" },
        new() { Code = 521,  Title = "petites Parisiennes" },
        new() { Code = 338,  Title = "petrkricek.cz" },
        new() { Code = 234,  Title = "photodromm" },
        new() { Code = 744,  Title = "photodromm Archives" },
        new() { Code = 27,   Title = "pier999" },
        new() { Code = 939,  Title = "pinupfiles" },
        new() { Code = 758,  Title = "pjgirls" },
        new() { Code = 858,  Title = "playboy Plus" },
        new() { Code = 197,  Title = "pleasure-archives" },
        new() { Code = 1572, Title = "porn-uk" },
        new() { Code = 1046, Title = "pornfidelity" },
        new() { Code = 1587, Title = "pornforce" },
        new() { Code = 1509, Title = "povmasters" },
        new() { Code = 46,   Title = "pretty4ever" },
        new() { Code = 1289, Title = "prettyfoxes" },
        new() { Code = 24,   Title = "prettynudes" },
        new() { Code = 29,   Title = "prettyvirgins" },
        new() { Code = 1039, Title = "princesscum" },
        new() { Code = 1401, Title = "publichandjobs" },
        new() { Code = 9,    Title = "purebeauty" },
        new() { Code = 1591, Title = "purecfnm" },
        new() { Code = 1134, Title = "puretaboo" },
        new() { Code = 1286, Title = "puritynaked" },
        new() { Code = 503,  Title = "querro" },
        new() { Code = 1328, Title = "rawcouples" },
        new() { Code = 463,  Title = "real8teens" },
        new() { Code = 966,  Title = "realbikinigirls" },
        new() { Code = 1521, Title = "realhotvr" },
        new() { Code = 419,  Title = "reality Kings" },
        new() { Code = 951,  Title = "realtimebondage" },
        new() { Code = 1547, Title = "realvr" },
        new() { Code = 711,  Title = "richard Avery" },
        new() { Code = 1574, Title = "rickysroom" },
        new() { Code = 413,  Title = "ridago" },
        new() { Code = 138,  Title = "Rigin Studio" },
        new() { Code = 215,  Title = "Ron Harris Archive" },
        new() { Code = 714,  Title = "Ron Harris" },
        new() { Code = 519,  Title = "rq-star" },
        new() { Code = 731,  Title = "rubbermodels" },
        new() { Code = 718,  Title = "rylsky Art" },
        new() { Code = 616,  Title = "sandysfantasies" },
        new() { Code = 830,  Title = "scandi-girl" },
        new() { Code = 41,   Title = "scandinavianfeet" },
        new() { Code = 1458, Title = "schoolpov" },
        new() { Code = 779,  Title = "scoreland" },
        new() { Code = 1526, Title = "screwmetoo" },
        new() { Code = 828,  Title = "secretnudistgirls" },
        new() { Code = 723,  Title = "secretvirgin" },
        new() { Code = 1487, Title = "seemomsuck" },
        new() { Code = 713,  Title = "sensualgirl" },
        new() { Code = 953,  Title = "sensualpain" },
        new() { Code = 670,  Title = "sexart" },
        new() { Code = 674,  Title = "sexart Video" },
        new() { Code = 1374, Title = "sexbabesvr" },
        new() { Code = 1524, Title = "sexmex" },
        new() { Code = 952,  Title = "sexuallybroken" },
        new() { Code = 599,  Title = "sexvideocasting" },
        new() { Code = 102,  Title = "sexy-babestv" },
        new() { Code = 1577, Title = "sexyukpornstars" },
        new() { Code = 1485, Title = "shadyspa" },
        new() { Code = 584,  Title = "shedontblush" },
        new() { Code = 820,  Title = "sheernudes" },
        new() { Code = 456,  Title = "sheisanangel" },
        new() { Code = 1473, Title = "shelovesblack" },
        new() { Code = 626,  Title = "ShowyBeauty" },
        new() { Code = 171,  Title = "silentviews" },
        new() { Code = 645,  Title = "silentviews2" },
        new() { Code = 119,  Title = "simonscans" },
        new() { Code = 890,  Title = "simplyanal" },
        new() { Code = 1343, Title = "sinematica" },
        new() { Code = 1568, Title = "sinfulfeet" },
        new() { Code = 250,  Title = "singoddess" },
        new() { Code = 638,  Title = "skinzerotica" },
        new() { Code = 232,  Title = "Skokoff" },
        new() { Code = 1494, Title = "slroriginals" },
        new() { Code = 1588, Title = "slutinspection" },
        new() { Code = 1506, Title = "smutpuppet" },
        new() { Code = 35,   Title = "snapgirls" },
        new() { Code = 829,  Title = "softorgasms" },
        new() { Code = 134,  Title = "solesofdirt" },
        new() { Code = 38,   Title = "spice-lab" },
        new() { Code = 1344, Title = "spizoo" },
        new() { Code = 1578, Title = "splatbukkake" },
        new() { Code = 1460, Title = "squirtingorgies" },
        new() { Code = 908,  Title = "stasyq" },
        new() { Code = 1029, Title = "stepmom Lessons" },
        new() { Code = 1453, Title = "steppov" },
        new() { Code = 893,  Title = "stepsiblingscaught" },
        new() { Code = 1397, Title = "straplez" },
        new() { Code = 748,  Title = "strictly Glamour" },
        new() { Code = 1400, Title = "strictlyhands" },
        new() { Code = 1398, Title = "strokies" },
        new() { Code = 745,  Title = "stunning18" },
        new() { Code = 1480, Title = "submissivex" },
        new() { Code = 872,  Title = "subspaceland" },
        new() { Code = 421,  Title = "suburbanamateurs" },
        new() { Code = 1402, Title = "superbemodels" },
        new() { Code = 225,  Title = "supernicegirls" },
        new() { Code = 589,  Title = "Suze.net" },
        new() { Code = 1489, Title = "swallowbay" },
        new() { Code = 505,  Title = "sweet-lilya" },
        new() { Code = 334,  Title = "sweetandnude" },
        new() { Code = 272,  Title = "sweetmodels" },
        new() { Code = 724,  Title = "sweetnaturenudes" },
        new() { Code = 1495, Title = "tabooheat" },
        new() { Code = 1445, Title = "tandalesbians" },
        new() { Code = 1037, Title = "teacherfucksteens" },
        new() { Code = 689,  Title = "team Skeet" },
        new() { Code = 596,  Title = "teasefactore" },
        new() { Code = 1486, Title = "teasepov" },
        new() { Code = 454,  Title = "teen-studio" },
        new() { Code = 186,  Title = "teenagedepot" },
        new() { Code = 1273, Title = "teenartclub" },
        new() { Code = 860,  Title = "teendreams" },
        new() { Code = 61,   Title = "teendreams Archive" },
        new() { Code = 1505, Title = "Teen Erotica" },
        new() { Code = 1047, Title = "Teen Fidelity" },
        new() { Code = 652,  Title = "Teengirls" },
        new() { Code = 451,  Title = "Teen Megaworld" },
        new() { Code = 401,  Title = "Teen Models" },
        new() { Code = 649,  Title = "TeenPornStorage" },
        new() { Code = 30,   Title = "Teenrotica" },
        new() { Code = 498,  Title = "Teens Legshow" },
        new() { Code = 452,  Title = "TeenSexMania" },
        new() { Code = 440,  Title = "TeenSexMovs" },
        new() { Code = 961,  Title = "Teen Starlet" },
        new() { Code = 921,  Title = "Teenstarleteuro" },
        new() { Code = 1499, Title = "Teentugs" },
        new() { Code = 1432, Title = "Tenshigao" },
        new() { Code = 1287, Title = "Test Shoots" },
        new() { Code = 1437, Title = "thebenefitmonkey" },
        new() { Code = 1226, Title = "theemilybloom" },
        new() { Code = 864,  Title = "theemilybloom Archive" },
        new() { Code = 1408, Title = "theflourishfetish" },
        new() { Code = 1409, Title = "theflourishpov" },
        new() { Code = 1410, Title = "theflourishxxx" },
        new() { Code = 1583, Title = "thelesbianexperience" },
        new() { Code = 648,  Title = "thelifeerotic" },
        new() { Code = 299,  Title = "TheNude" },
        new() { Code = 637,  Title = "theredchair" },
        new() { Code = 917,  Title = "theredfoxlife" },
        new() { Code = 685,  Title = "thisisglamour" },
        new() { Code = 884,  Title = "thisyearsmodel" },
        new() { Code = 1090, Title = "throated" },
        new() { Code = 1546, Title = "throatshots" },
        new() { Code = 612,  Title = "tigerrjuggs" },
        new() { Code = 465,  Title = "tle Archives" },
        new() { Code = 1543, Title = "tmwpov" },
        new() { Code = 904,  Title = "tmwvrnet" },
        new() { Code = 889,  Title = "tokyodoll" },
        new() { Code = 1525, Title = "toosexy" },
        new() { Code = 954,  Title = "topgrl" },
        new() { Code = 198,  Title = "torridart" },
        new() { Code = 1375, Title = "touchmywife" },
        new() { Code = 590,  Title = "trickymasseur" },
        new() { Code = 1528, Title = "trikepatrol" },
        new() { Code = 468,  Title = "tsm Models" },
        new() { Code = 1399, Title = "tugcasting" },
        new() { Code = 1555, Title = "tugpass" },
        new() { Code = 1529, Title = "tuktukpatrol" },
        new() { Code = 78,   Title = "Twistys" },
        new() { Code = 583,  Title = "Tyingart" },
        new() { Code = 1579, Title = "Ukpornparty" },
        new() { Code = 1576, Title = "Ukxxxpass" },
        new() { Code = 1564, Title = "Upskirtglamour" },
        new() { Code = 922,  Title = "Upskirtjerk" },
        new() { Code = 653,  Title = "Venbo" },
        new() { Code = 865,  Title = "Vipissy" },
        new() { Code = 190,  Title = "Vipnudes" },
        new() { Code = 853,  Title = "Virtuagirl3k" },
        new() { Code = 755,  Title = "Virtualrealitychannel" },
        new() { Code = 1436, Title = "Virtualrealjapan" },
        new() { Code = 1435, Title = "Virtualrealpassion" },
        new() { Code = 1434, Title = "Virtualrealporn" },
        new() { Code = 1381, Title = "Virtual taboo" },
        new() { Code = 116,  Title = "Vivthomas" },
        new() { Code = 740,  Title = "Vivthomas Video" },
        new() { Code = 1431, Title = "Vlogxxx" },
        new() { Code = 1277, Title = "Vrbangers" },
        new() { Code = 1372, Title = "Vrfirsttimer" },
        new() { Code = 1394, Title = "Vrfootfetish" },
        new() { Code = 739,  Title = "VT Archives" },
        new() { Code = 196,  Title = "Vulis-archives" },
        new() { Code = 832,  Title = "Wakeupnfuck" },
        new() { Code = 154,  Title = "Walterbosque" },
        new() { Code = 727,  Title = "Wankitnow" },
        new() { Code = 1420, Title = "Wankitnowvr" },
        new() { Code = 1441, Title = "Wankzvr" },
        new() { Code = 13,   Title = "Watch4beauty" },
        new() { Code = 1479, Title = "Watchyoujerk" },
        new() { Code = 662,  Title = "Weliketosuck" },
        new() { Code = 523,  Title = "Wet2nude" },
        new() { Code = 691,  Title = "Wetandpissy" },
        new() { Code = 485,  Title = "Wetandpuffy" },
        new() { Code = 522,  Title = "Wetspirit" },
        new() { Code = 1379, Title = "Wicked" },
        new() { Code = 436,  Title = "Woodman Casting X" },
        new() { Code = 763,  Title = "X-angels" },
        new() { Code = 329,  Title = "X-art" },
        new() { Code = 1230, Title = "Xillimite" },
        new() { Code = 502,  Title = "Xstyle Beauties" },
        new() { Code = 1552, Title = "Youngermommy" },
        new() { Code = 210,  Title = "Zemani" },
        new() { Code = 325,  Title = "Zemani Video" },
        new() { Code = 673,  Title = "Zenia Herzog" },
        new() { Code = 1333, Title = "Zexyvr" },
        new() { Code = 756,  Title = "Zishy" },
        new() { Code = 1223, Title = "Zlata" },
    };

    #endregion

    #region Object members

    public override string ToString() => Title;

    #endregion
}
