//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be IPv4.
        /// </summary>
        internal static string AddressMustBeIPv4 {
            get {
                return ResourceManager.GetString("AddressMustBeIPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : address must be IPv4 but given .
        /// </summary>
        internal static string AddressMustBeIPv4ButGiven {
            get {
                return ResourceManager.GetString("AddressMustBeIPv4ButGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be IPv6.
        /// </summary>
        internal static string AddressMustBeIPv6 {
            get {
                return ResourceManager.GetString("AddressMustBeIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : address must be IPv6 but given .
        /// </summary>
        internal static string AddressMustBeIPv6ButGiven {
            get {
                return ResourceManager.GetString("AddressMustBeIPv6ButGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad symbol.
        /// </summary>
        internal static string BadSymbol {
            get {
                return ResourceManager.GetString("BadSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get property: {0}.
        /// </summary>
        internal static string Can_t_get_property {
            get {
                return ResourceManager.GetString("Can_t_get_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t find field  .
        /// </summary>
        internal static string CantFindField {
            get {
                return ResourceManager.GetString("CantFindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t find property .
        /// </summary>
        internal static string CantFindProperty {
            get {
                return ResourceManager.GetString("CantFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve address.
        /// </summary>
        internal static string CantResolveAddress {
            get {
                return ResourceManager.GetString("CantResolveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t resolve address.
        /// </summary>
        internal static string CantResolveAddress2 {
            get {
                return ResourceManager.GetString("CantResolveAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve IPv4 address.
        /// </summary>
        internal static string CantResolveIPv4Address {
            get {
                return ResourceManager.GetString("CantResolveIPv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t resolve IPv4 address.
        /// </summary>
        internal static string CantResolveIPv4Address2 {
            get {
                return ResourceManager.GetString("CantResolveIPv4Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve IPv6 address.
        /// </summary>
        internal static string CantResolveIPv6Address {
            get {
                return ResourceManager.GetString("CantResolveIPv6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t resolve IPv6 address.
        /// </summary>
        internal static string CantResolveIPv6Address2 {
            get {
                return ResourceManager.GetString("CantResolveIPv6Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : error reading socket.
        /// </summary>
        internal static string ErrorReadingSocket {
            get {
                return ResourceManager.GetString("ErrorReadingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method for {0}.
        /// </summary>
        internal static string No_method_for {
            get {
                return ResourceManager.GetString("No_method_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} doesn&apos;t exist..
        /// </summary>
        internal static string ResourceDoesntExist {
            get {
                return ResourceManager.GetString("ResourceDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket reading error.
        /// </summary>
        internal static string SocketReadingError {
            get {
                return ResourceManager.GetString("SocketReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected mode=.
        /// </summary>
        internal static string UnexpectedMode {
            get {
                return ResourceManager.GetString("UnexpectedMode", resourceCulture);
            }
        }
    }
}
