// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

// ReSharper disable CheckNamespace
// ReSharper disable CommentTypo
// ReSharper disable IdentifierTypo
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global

/* PSMsgID.cs --
 * Ars Magna project, http://arsmagna.ru
 */

namespace PdfSharpCore
{
    /// <summary>
    /// Represents IDs for error and diagnostic messages generated by PdfSharpCore.
    /// </summary>
    // ReSharper disable once InconsistentNaming
    enum PSMsgID
    {
        // ----- General Messages ---------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        SampleMessage1,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        SampleMessage2,

        // ----- XGraphics Messages ---------------------------------------------------------------

        // ----- PDF Messages ----------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        NameMustStartWithSlash,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UserOrOwnerPasswordRequired,

        // ----- PdfParser Messages -------------------------------------------------------------------

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UnexpectedToken,

        /// <summary>
        /// PSMsgID.
        /// </summary>
        UnknownEncryption,
    }
}