//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagedIrbis5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagedIrbis5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string AbstractEngine_NotConnected {
            get {
                return ResourceManager.GetString("AbstractEngine_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : not connected.
        /// </summary>
        internal static string AbstractEngine_NotConnected2 {
            get {
                return ResourceManager.GetString("AbstractEngine_NotConnected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  failed.
        /// </summary>
        internal static string AbstractEngine_StandardExecution_Failed {
            get {
                return ResourceManager.GetString("AbstractEngine_StandardExecution_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected.
        /// </summary>
        internal static string AlreadyConnected {
            get {
                return ResourceManager.GetString("AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : empty record detected.
        /// </summary>
        internal static string BatchAccessor_EmptyRecordDetected {
            get {
                return ResourceManager.GetString("BatchAccessor_EmptyRecordDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some records not retrieved.
        /// </summary>
        internal static string BatchAccessor_SomeRecordsNotRetrieved {
            get {
                return ResourceManager.GetString("BatchAccessor_SomeRecordsNotRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken network event.
        /// </summary>
        internal static string BrokenNetworkEvent {
            get {
                return ResourceManager.GetString("BrokenNetworkEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t read first line of the response.
        /// </summary>
        internal static string CantReadFirstLineOfTheResponse {
            get {
                return ResourceManager.GetString("CantReadFirstLineOfTheResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resolve host .
        /// </summary>
        internal static string CantResolveHost {
            get {
                return ResourceManager.GetString("CantResolveHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionCreator not set.
        /// </summary>
        internal static string ConnectionCreatorNotSet {
            get {
                return ResourceManager.GetString("ConnectionCreatorNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not set.
        /// </summary>
        internal static string DatabaseNotSet {
            get {
                return ResourceManager.GetString("DatabaseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory not exist: .
        /// </summary>
        internal static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty response.
        /// </summary>
        internal static string EmptyResponse {
            get {
                return ResourceManager.GetString("EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during actualization.
        /// </summary>
        internal static string ErrorDescription_ActualizationError {
            get {
                return ResourceManager.GetString("ErrorDescription_ActualizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during autoin.gbl processing.
        /// </summary>
        internal static string ErrorDescription_AutoinGblError {
            get {
                return ResourceManager.GetString("ErrorDescription_AutoinGblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup creation error.
        /// </summary>
        internal static string ErrorDescription_BackupCreationError {
            get {
                return ResourceManager.GetString("ErrorDescription_BackupCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restore error.
        /// </summary>
        internal static string ErrorDescription_BackupRestoreError {
            get {
                return ResourceManager.GetString("ErrorDescription_BackupRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad client identifier.
        /// </summary>
        internal static string ErrorDescription_BadClientIdentifier {
            get {
                return ResourceManager.GetString("ErrorDescription_BadClientIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad password.
        /// </summary>
        internal static string ErrorDescription_BadPassword {
            get {
                return ResourceManager.GetString("ErrorDescription_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad shelf number.
        /// </summary>
        internal static string ErrorDescription_BadShelfNumber {
            get {
                return ResourceManager.GetString("ErrorDescription_BadShelfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad shelf size.
        /// </summary>
        internal static string ErrorDescription_BadShelfSize {
            get {
                return ResourceManager.GetString("ErrorDescription_BadShelfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad term.
        /// </summary>
        internal static string ErrorDescription_BadTerm {
            get {
                return ResourceManager.GetString("ErrorDescription_BadTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is already registered.
        /// </summary>
        internal static string ErrorDescription_ClientAlreadyRegistered {
            get {
                return ResourceManager.GetString("ErrorDescription_ClientAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not allowed.
        /// </summary>
        internal static string ErrorDescription_ClientNotAllowed {
            get {
                return ResourceManager.GetString("ErrorDescription_ClientNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client doesn&apos;t in use.
        /// </summary>
        internal static string ErrorDescription_ClientNotInUse {
            get {
                return ResourceManager.GetString("ErrorDescription_ClientNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not registered.
        /// </summary>
        internal static string ErrorDescription_ClientNotRegistered {
            get {
                return ResourceManager.GetString("ErrorDescription_ClientNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is exclusively locked.
        /// </summary>
        internal static string ErrorDescription_DatabaseIsLocked {
            get {
                return ResourceManager.GetString("ErrorDescription_DatabaseIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary creation error.
        /// </summary>
        internal static string ErrorDescription_DictionaryCreationError {
            get {
                return ResourceManager.GetString("ErrorDescription_DictionaryCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary loading error.
        /// </summary>
        internal static string ErrorDescription_DictionaryLoadingError {
            get {
                return ResourceManager.GetString("ErrorDescription_DictionaryLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global correction: bad tag.
        /// </summary>
        internal static string ErrorDescription_ERR_GBL_MET {
            get {
                return ResourceManager.GetString("ErrorDescription_ERR_GBL_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global correction: bad rep tag.
        /// </summary>
        internal static string ErrorDescription_ERR_GBL_REP {
            get {
                return ResourceManager.GetString("ErrorDescription_ERR_GBL_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is absent.
        /// </summary>
        internal static string ErrorDescription_FieldIsAbsent {
            get {
                return ResourceManager.GetString("ErrorDescription_FieldIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not exist.
        /// </summary>
        internal static string ErrorDescription_FileNotExist {
            get {
                return ResourceManager.GetString("ErrorDescription_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First term in the list.
        /// </summary>
        internal static string ErrorDescription_FirstTerm {
            get {
                return ResourceManager.GetString("ErrorDescription_FirstTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error.
        /// </summary>
        internal static string ErrorDescription_GeneralError {
            get {
                return ResourceManager.GetString("ErrorDescription_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given MFN is outside the database range.
        /// </summary>
        internal static string ErrorDescription_GivenMfnOutsideTheDatabaseRange {
            get {
                return ResourceManager.GetString("ErrorDescription_GivenMfnOutsideTheDatabaseRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global correction parameter error.
        /// </summary>
        internal static string ErrorDescription_GlobalCorrectionParameterError {
            get {
                return ResourceManager.GetString("ErrorDescription_GlobalCorrectionParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index file error.
        /// </summary>
        internal static string ErrorDescription_IfpError {
            get {
                return ResourceManager.GetString("ErrorDescription_IfpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last term in the list.
        /// </summary>
        internal static string ErrorDescription_LastTerm {
            get {
                return ResourceManager.GetString("ErrorDescription_LastTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFN outside the database range.
        /// </summary>
        internal static string ErrorDescription_MfnOutsideTheDatabaseRange {
            get {
                return ResourceManager.GetString("ErrorDescription_MfnOutsideTheDatabaseRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master file error.
        /// </summary>
        internal static string ErrorDescription_MstError {
            get {
                return ResourceManager.GetString("ErrorDescription_MstError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        internal static string ErrorDescription_NoError {
            get {
                return ResourceManager.GetString("ErrorDescription_NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous version of the record.
        /// </summary>
        internal static string ErrorDescription_NoPreviousVersionOfTheRecord {
            get {
                return ResourceManager.GetString("ErrorDescription_NoPreviousVersionOfTheRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal return.
        /// </summary>
        internal static string ErrorDescription_NormalReturn {
            get {
                return ResourceManager.GetString("ErrorDescription_NormalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator thread error.
        /// </summary>
        internal static string ErrorDescription_ProcessError {
            get {
                return ResourceManager.GetString("ErrorDescription_ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error.
        /// </summary>
        internal static string ErrorDescription_ProtocolError {
            get {
                return ResourceManager.GetString("ErrorDescription_ProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read error.
        /// </summary>
        internal static string ErrorDescription_ReadError {
            get {
                return ResourceManager.GetString("ErrorDescription_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is blocked.
        /// </summary>
        internal static string ErrorDescription_RecordIsBlocked {
            get {
                return ResourceManager.GetString("ErrorDescription_RecordIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is logically deleted.
        /// </summary>
        internal static string ErrorDescription_RecordIsLogicallyDeleted {
            get {
                return ResourceManager.GetString("ErrorDescription_RecordIsLogicallyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is physically deleted.
        /// </summary>
        internal static string ErrorDescription_RecordIsPhysicallyDeleted {
            get {
                return ResourceManager.GetString("ErrorDescription_RecordIsPhysicallyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record version mismatch.
        /// </summary>
        internal static string ErrorDescription_RecordVersionError {
            get {
                return ResourceManager.GetString("ErrorDescription_RecordVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server execution error.
        /// </summary>
        internal static string ErrorDescription_ServerExecutionError {
            get {
                return ResourceManager.GetString("ErrorDescription_ServerExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is overloaded.
        /// </summary>
        internal static string ErrorDescription_ServerOverloaded {
            get {
                return ResourceManager.GetString("ErrorDescription_ServerOverloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during sorting.
        /// </summary>
        internal static string ErrorDescription_SortingError {
            get {
                return ResourceManager.GetString("ErrorDescription_SortingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term doesn&apos;t exist.
        /// </summary>
        internal static string ErrorDescription_TermNotExist {
            get {
                return ResourceManager.GetString("ErrorDescription_TermNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string ErrorDescription_UnknownError {
            get {
                return ResourceManager.GetString("ErrorDescription_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation access denied.
        /// </summary>
        internal static string ErrorDescription_WorkstationAccesDenied {
            get {
                return ResourceManager.GetString("ErrorDescription_WorkstationAccesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write error.
        /// </summary>
        internal static string ErrorDescription_WriteError {
            get {
                return ResourceManager.GetString("ErrorDescription_WriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : bad tag=.
        /// </summary>
        internal static string FieldTag_Verify_BadTag1 {
            get {
                return ResourceManager.GetString("FieldTag_Verify_BadTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bad tag=.
        /// </summary>
        internal static string FieldTag_Verify_BadTag2 {
            get {
                return ResourceManager.GetString("FieldTag_Verify_BadTag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Field.Value: .
        /// </summary>
        internal static string FieldValue_Verify_BadFieldValue {
            get {
                return ResourceManager.GetString("FieldValue_Verify_BadFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : bad value=.
        /// </summary>
        internal static string FieldValue_Verify_BadValue {
            get {
                return ResourceManager.GetString("FieldValue_Verify_BadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set socket while connected.
        /// </summary>
        internal static string IrbisConnection_CantSetSocketWhileConnected {
            get {
                return ResourceManager.GetString("IrbisConnection_CantSetSocketWhileConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted state is null.
        /// </summary>
        internal static string IrbisConnection_DecryptedStateIsNull {
            get {
                return ResourceManager.GetString("IrbisConnection_DecryptedStateIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no record retrieved.
        /// </summary>
        internal static string IrbisConnection_NoRecordRetrieved {
            get {
                return ResourceManager.GetString("IrbisConnection_NoRecordRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result record is null.
        /// </summary>
        internal static string IrbisConnection_ResultRecordIsNull {
            get {
                return ResourceManager.GetString("IrbisConnection_ResultRecordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : not single-byte encoding.
        /// </summary>
        internal static string IrbisEncoding_NotSingleByteEncoding {
            get {
                return ResourceManager.GetString("IrbisEncoding_NotSingleByteEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database not specified.
        /// </summary>
        internal static string IrbisNetworkUtility_DatabaseNotSpecified {
            get {
                return ResourceManager.GetString("IrbisNetworkUtility_DatabaseNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty record detected.
        /// </summary>
        internal static string IrbisNetworkUtility_EmptyRecordDetected {
            get {
                return ResourceManager.GetString("IrbisNetworkUtility_EmptyRecordDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record is null.
        /// </summary>
        internal static string IrbisNetworkUtility_RecordIsNull {
            get {
                return ResourceManager.GetString("IrbisNetworkUtility_RecordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : non overriden.
        /// </summary>
        internal static string IrbisProvider_NonOverriden {
            get {
                return ResourceManager.GetString("IrbisProvider_NonOverriden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specification list is empty.
        /// </summary>
        internal static string ListFilesCommand_SpecificationListIsEmpty {
            get {
                return ResourceManager.GetString("ListFilesCommand_SpecificationListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no files specified.
        /// </summary>
        internal static string NoFilesSpecified {
            get {
                return ResourceManager.GetString("NoFilesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password not specified.
        /// </summary>
        internal static string PasswordNotSpecified {
            get {
                return ResourceManager.GetString("PasswordNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : can&apos;t find type: .
        /// </summary>
        internal static string ProviderManager_CanTFindType {
            get {
                return ResourceManager.GetString("ProviderManager_CanTFindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find type: .
        /// </summary>
        internal static string ProviderManager_CantFindType2 {
            get {
                return ResourceManager.GetString("ProviderManager_CantFindType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IrbisProvider configuration key not specified.
        /// </summary>
        internal static string ProviderManager_IrbisProviderConfigurationKeyNotSpecified {
            get {
                return ResourceManager.GetString("ProviderManager_IrbisProviderConfigurationKeyNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : provider name not specified.
        /// </summary>
        internal static string ProviderManager_ProviderNameNotSpecified {
            get {
                return ResourceManager.GetString("ProviderManager_ProviderNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : provider not found: .
        /// </summary>
        internal static string ProviderManager_ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderManager_ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider not found: .
        /// </summary>
        internal static string ProviderManager_ProviderNotFound2 {
            get {
                return ResourceManager.GetString("ProviderManager_ProviderNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file name not specified.
        /// </summary>
        internal static string ReadBinaryFileCommand_FileNameNotSpecified {
            get {
                return ResourceManager.GetString("ReadBinaryFileCommand_FileNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no binary data received.
        /// </summary>
        internal static string ReadBinaryFileCommand_NoBinaryDataReceived {
            get {
                return ResourceManager.GetString("ReadBinaryFileCommand_NoBinaryDataReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of terms == null.
        /// </summary>
        internal static string ReadPostingsCommand_ListOfTermsNull {
            get {
                return ResourceManager.GetString("ReadPostingsCommand_ListOfTermsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record too long.
        /// </summary>
        internal static string RecordTooLong {
            get {
                return ResourceManager.GetString("RecordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : bad format=.
        /// </summary>
        internal static string ServerResponse_BadFormat {
            get {
                return ResourceManager.GetString("ServerResponse_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : empty response.
        /// </summary>
        internal static string SmartRead_EmptyResponse {
            get {
                return ResourceManager.GetString("SmartRead_EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : expected=.
        /// </summary>
        internal static string SmartRead_Expected {
            get {
                return ResourceManager.GetString("SmartRead_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , readed=.
        /// </summary>
        internal static string SmartRead_Readed {
            get {
                return ResourceManager.GetString("SmartRead_Readed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record list is empty.
        /// </summary>
        internal static string UnlockRecordsCommand_RecordListIsEmpty {
            get {
                return ResourceManager.GetString("UnlockRecordsCommand_RecordListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserList not set.
        /// </summary>
        internal static string UserListNotSet {
            get {
                return ResourceManager.GetString("UserListNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username not specified.
        /// </summary>
        internal static string UsernameNotSpecified {
            get {
                return ResourceManager.GetString("UsernameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is absent.
        /// </summary>
        internal static string VerifyFormat_TextIsAbsent {
            get {
                return ResourceManager.GetString("VerifyFormat_TextIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : text is absent.
        /// </summary>
        internal static string VerifyFormat_TextIsAbsent2 {
            get {
                return ResourceManager.GetString("VerifyFormat_TextIsAbsent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database not set.
        /// </summary>
        internal static string WriteRecordsCommand_DatabaseNotSet {
            get {
                return ResourceManager.GetString("WriteRecordsCommand_DatabaseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no records given.
        /// </summary>
        internal static string WriteRecordsCommand_NoRecordsGiven {
            get {
                return ResourceManager.GetString("WriteRecordsCommand_NoRecordsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too many records.
        /// </summary>
        internal static string WriteRecordsCommand_TooManyRecords {
            get {
                return ResourceManager.GetString("WriteRecordsCommand_TooManyRecords", resourceCulture);
            }
        }
    }
}
