name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build
      run: dotnet build --configuration Release Source/ManagedIrbis5.sln

    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release Source/ManagedIrbis5.sln

    - name: Benchmark
      run: dotnet run --no-build --no-restore --configuration Release --project Source/Benchmarks/CoreBenchmarks/CoreBenchmarks.csproj

    - name: Pack
      run: dotnet pack --no-build --no-restore --configuration Release Source/ManagedIrbis5.sln
