name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301
        
    - name: Setup .NET 6 Preview
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.5.21302.13

    - name: Build
      run: dotnet build --configuration Release Source/ManagedIrbis5.sln

    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release Source/ManagedIrbis5.sln

    - name: PFT tests
      run: dotnet run --no-build --no-restore --configuration Release --project Source/Tests/PftTests/PftTests.csproj

    - name: Pack
      run: dotnet pack --no-build --no-restore --configuration Release Source/ManagedIrbis5.sln
