name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101

    - name: Build
      run: dotnet build --configuration Release Source/ManagedIrbis5.sln

    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release Source/ManagedIrbis5.sln

    - name: PFT tests
      run: dotnet run --no-build --no-restore --configuration Release --project Source/Tests/PftTests/PftTests.csproj
      
    - name: Barsik tests
      run: dotnet run --no-build --no-restore --configuration Release --project Source/Tests/BarsikTestRunner/BarsikTestRunner.csproj

    - name: Pack
      run: dotnet pack --no-build --no-restore --configuration Release Source/ManagedIrbis5.sln
